
const { v4: uuidv4 } = require('uuid');


const store = {
  bots: [],
  cases: [],
  items: [],
  battles: {},
  market_items: [
    {"id":"63","market_hash_name":"AK-47 | Neon Revolution (FT)","cat":"Emerlad"},
    {"id":"64","market_hash_name":"Tec-9 | Blue Blast (Field-Tested)","cat":"Emerlad"},
    {"id":"65","market_hash_name":"StatTrak™ Glock-18 | Shinobu (Field-Tested)","cat":"Emerlad"},
    {"id":"67","market_hash_name":"MAG-7 | Insomnia (Field-Tested)","cat":"Emerlad"},
    {"id":"68","market_hash_name":"MAC-10 | Saibā Oni (Factory New)","cat":"Emerlad"},
    {"id":"69","market_hash_name":"Sealed Graffiti | Keep the Change (Cash Green)","cat":"Emerlad"},
    {"id":"70","market_hash_name":"Sealed Graffiti | Bling (Battle Green)","cat":"Emerlad"},
    {"id":"71","market_hash_name":"Shanghai 2024 Coin","cat":"Emerlad"},
    {"id":"73","market_hash_name":"Operation Broken Fang Challenge Coin","cat":"Emerlad"},
    {"id":"74","market_hash_name":"Copenhagen 2024 Gold Coin","cat":"Emerlad"},
    {"id":"75","market_hash_name":"2024 Service Medal","cat":"Emerlad"},
    {"id":"76","market_hash_name":"Music Kit | Valve, CS:GO","cat":"Emerlad"},
    {"id":"77","market_hash_name":"Global Offensive Badge","cat":"Emerlad"},
    {"id":"78","market_hash_name":"Paris 2023 Gold Coin","cat":"Emerlad"},
    {"id":"79","market_hash_name":"2023 Service Medal","cat":"Emerlad"},
    {"id":"80","market_hash_name":"10 Year Birthday Coin","cat":"Emerlad"},
    {"id":"81","market_hash_name":"Antwerp 2022 Gold Coin","cat":"Emerlad"},
    {"id":"82","market_hash_name":"StatTrak™ P250 | Visions (Field-Tested)","cat":"Emerlad"},
    {"id":"83","market_hash_name":"Nova | Mandrel (Field-Tested)","cat":"Emerlad"},
    {"id":"85","market_hash_name":"Diamond Operation Riptide Coin","cat":"Emerlad"},
    {"id":"87","market_hash_name":"MAC-10 | Storm Camo (Field-Tested)","cat":"Emerlad"},
    {"id":"88","market_hash_name":"Test","cat":"Emerlad"},
    {"id":"89","market_hash_name":"Chroma Case","cat":"Emerlad"},
    {"id":"90","market_hash_name":"Genuine Alyx Pin","cat":"Emerlad"},
    {"id":"91","market_hash_name":"Music Kit | Half-Life: Alyx, Anti-Citizen","cat":"Emerlad"},
    {"id":"92","market_hash_name":"Loyalty Badge","cat":"Emerlad"},
    {"id":"93","market_hash_name":"10 Year Veteran Coin","cat":"Emerlad"},
    {"id":"94","market_hash_name":"Revolver Case","cat":"Emerlad"},
    {"id":"95","market_hash_name":"Operation Phoenix Weapon Case","cat":"Emerlad"},
    {"id":"96","market_hash_name":"eSports 2014 Summer Case","cat":"Emerlad"},
    {"id":"97","market_hash_name":"AUG | Storm (Minimal Wear)","cat":"Emerlad"},
    {"id":"98","market_hash_name":"P2000 | Grassland Leaves (Field-Tested)","cat":"Emerlad"},
    {"id":"99","market_hash_name":"Nova | Walnut (Field-Tested)","cat":"Emerlad"},
    {"id":"100","market_hash_name":"MAG-7 | Sand Dune (Field-Tested)","cat":"Emerlad"},
    {"id":"101","market_hash_name":"MAC-10 | Tornado (Field-Tested)","cat":"Emerlad"},
    {"id":"102","market_hash_name":"XM1014 | Grassland (Field-Tested)","cat":"Emerlad"},
    {"id":"103","market_hash_name":"Music Kit | Darren Korb, Hades Music Kit","cat":"Emerlad"},
    {"id":"104","market_hash_name":"Music Kit | Halo, The Master Chief Collection","cat":"Emerlad"},
    {"id":"105","market_hash_name":"AK-47 | Point Disarray (Field-Tested)","cat":"Emerlad"},
    {"id":"106","market_hash_name":"M4A1-S | Nitro (Field-Tested)","cat":"Emerlad"},
    {"id":"107","market_hash_name":"Spectrum Case","cat":"Emerlad"},
    {"id":"108","market_hash_name":"Gamma 2 Case","cat":"Emerlad"},
    {"id":"109","market_hash_name":"Glove Case","cat":"Emerlad"},
    {"id":"110","market_hash_name":"Sealed Graffiti | Karambit (Frog Green)","cat":"Emerlad"},
    {"id":"111","market_hash_name":"Gamma Case","cat":"Emerlad"},
    {"id":"112","market_hash_name":"Sealed Graffiti | GTG (Monarch Blue)","cat":"Emerlad"},
    {"id":"113","market_hash_name":"P250 | Sand Dune (Field-Tested)","cat":"Emerlad"},
    {"id":"114","market_hash_name":"Chroma 3 Case","cat":"Emerlad"},
    {"id":"115","market_hash_name":"Galil AR | VariCamo (Battle-Scarred)","cat":"Emerlad"},
    {"id":"116","market_hash_name":"MP7 | Anodized Navy (Factory New)","cat":"Emerlad"},
    {"id":"117","market_hash_name":"Sealed Graffiti | GTG (Tracer Yellow)","cat":"Emerlad"},
    {"id":"118","market_hash_name":"Sealed Graffiti | NaCl (Shark White)","cat":"Emerlad"},
    {"id":"119","market_hash_name":"Sealed Graffiti | Take Flight (Bazooka Pink)","cat":"Emerlad"},
    {"id":"120","market_hash_name":"Sealed Graffiti | Eat It (Desert Amber)","cat":"Emerlad"},
    {"id":"121","market_hash_name":"Sealed Graffiti | Speechless (Cash Green)","cat":"Emerlad"},
    {"id":"122","market_hash_name":"Sealed Graffiti | GTG (Monster Purple)","cat":"Emerlad"},
    {"id":"123","market_hash_name":"Sealed Graffiti | X-Knives (Desert Amber)","cat":"Emerlad"},
    {"id":"124","market_hash_name":"Sealed Graffiti | Quickdraw (War Pig Pink)","cat":"Emerlad"},
    {"id":"125","market_hash_name":"Sealed Graffiti | Heart (Blood Red)","cat":"Emerlad"},
    {"id":"126","market_hash_name":"Sealed Graffiti | X-Axes (War Pig Pink)","cat":"Emerlad"},
    {"id":"127","market_hash_name":"Sealed Graffiti | Speechless (Shark White)","cat":"Emerlad"},
    {"id":"128","market_hash_name":"Sealed Graffiti | Ninja (Princess Pink)","cat":"Emerlad"},
    {"id":"129","market_hash_name":"SSG 08 | Blue Spruce (Minimal Wear)","cat":"Emerlad"},
    {"id":"130","market_hash_name":"Sealed Graffiti | 8-Ball (War Pig Pink)","cat":"Emerlad"},
    {"id":"131","market_hash_name":"AUG | Storm (Field-Tested)","cat":"Emerlad"},
    {"id":"132","market_hash_name":"R8 Revolver | Bone Mask (Field-Tested)","cat":"Emerlad"},
    {"id":"133","market_hash_name":"SSG 08 | Blue Spruce (Battle-Scarred)","cat":"Emerlad"},
    {"id":"134","market_hash_name":"Negev | Army Sheen (Minimal Wear)","cat":"Emerlad"},
    {"id":"135","market_hash_name":"P90 | Sand Spray (Field-Tested)","cat":"Emerlad"},
    {"id":"136","market_hash_name":"Nova | Sand Dune (Minimal Wear)","cat":"Emerlad"},
    {"id":"137","market_hash_name":"MP9 | Sand Dashed (Field-Tested)","cat":"Emerlad"},
    {"id":"138","market_hash_name":"Dual Berettas | Contractor (Field-Tested)","cat":"Emerlad"},
    {"id":"139","market_hash_name":"SCAR-20 | Contractor (Field-Tested)","cat":"Emerlad"},
    {"id":"140","market_hash_name":"G3SG1 | Jungle Dashed (Field-Tested)","cat":"Emerlad"},
    {"id":"141","market_hash_name":"MAC-10 | Candy Apple (Minimal Wear)","cat":"Emerlad"},
    {"id":"142","market_hash_name":"Tec-9 | Urban DDPAT (Minimal Wear)","cat":"Emerlad"},
    {"id":"143","market_hash_name":"PP-Bizon | Sand Dashed (Field-Tested)","cat":"Emerlad"},
    {"id":"144","market_hash_name":"XM1014 | Blue Spruce (Field-Tested)","cat":"Emerlad"},
    {"id":"145","market_hash_name":"Desert Eagle | Mudder (Minimal Wear)","cat":"Emerlad"},
    {"id":"146","market_hash_name":"MP7 | Army Recon (Field-Tested)","cat":"Emerlad"},
    {"id":"147","market_hash_name":"StatTrak™ Galil AR | Rocket Pop (Field-Tested)","cat":"Emerlad"},
    {"id":"148","market_hash_name":"P2000 | Pulse (Minimal Wear)","cat":"Emerlad"},
    {"id":"149","market_hash_name":"P250 | Sand Dune (Field-Tested)","cat":"Emerlad"},
    {"id":"150","market_hash_name":"Sawed-Off | Forest DDPAT (Battle-Scarred)","cat":"Emerlad"},
    {"id":"151","market_hash_name":"FAMAS | Cyanospatter (Field-Tested)","cat":"Emerlad"},
    {"id":"152","market_hash_name":"SG 553 | Army Sheen (Factory New)","cat":"Emerlad"},
    {"id":"153","market_hash_name":"C4 Explosive","cat":"Emerlad"},
    {"id":"154","market_hash_name":"Operation Hydra Challenge Coin","cat":"Emerlad"},
    {"id":"155","market_hash_name":"M249 | Nebula Crusader (Field-Tested)","cat":"Emerlad"},
    {"id":"156","market_hash_name":"MAG-7 | Cobalt Core (Field-Tested)","cat":"Emerlad"},
    {"id":"157","market_hash_name":"SG 553 | Cyrex (Well-Worn)","cat":"Emerlad"},
    {"id":"158","market_hash_name":"FAMAS | Colony (Battle-Scarred)","cat":"Emerlad"},
    {"id":"159","market_hash_name":"SG 553 | Army Sheen (Factory New)","cat":"Emerlad"},
    {"id":"160","market_hash_name":"Five-SeveN | Forest Night (Field-Tested)","cat":"Emerlad"},
    {"id":"161","market_hash_name":"PP-Bizon | Urban Dashed (Field-Tested)","cat":"Emerlad"},
    {"id":"162","market_hash_name":"Operation Wildfire Challenge Coin","cat":"Emerlad"},
    {"id":"163","market_hash_name":"Operation Bloodhound Challenge Coin","cat":"Emerlad"},
    {"id":"164","market_hash_name":"Operation Vanguard Challenge Coin","cat":"Emerlad"},
    {"id":"165","market_hash_name":"Sealed Graffiti | Worry (Frog Green)","cat":"Emerlad"},
    {"id":"166","market_hash_name":"Fracture Case","cat":"Emerlad"},
    {"id":"167","market_hash_name":"Clutch Case","cat":"Emerlad"},
    {"id":"168","market_hash_name":"Sealed Graffiti | Take Flight (Princess Pink)","cat":"Emerlad"},
    {"id":"169","market_hash_name":"Danger Zone Case","cat":"Emerlad"},
    {"id":"170","market_hash_name":"Sawed-Off | Forest DDPAT (Minimal Wear)","cat":"Emerlad"},
    {"id":"171","market_hash_name":"Horizon Case","cat":"Emerlad"},
    {"id":"172","market_hash_name":"Sealed Graffiti | Tilt (Shark White)","cat":"Emerlad"},
    {"id":"173","market_hash_name":"Five-SeveN | Forest Night (Minimal Wear)","cat":"Emerlad"},
    {"id":"174","market_hash_name":"Tec-9 | Groundwater (Battle-Scarred)","cat":"Emerlad"},
    {"id":"175","market_hash_name":"Sealed Graffiti | Karambit (Brick Red)","cat":"Emerlad"},
    {"id":"176","market_hash_name":"Operation Breakout Weapon Case","cat":"Emerlad"},
    {"id":"177","market_hash_name":"G3SG1 | Polar Camo (Field-Tested)","cat":"Emerlad"},
    {"id":"178","market_hash_name":"CZ75-Auto | The Fuschia Is Now","cat":"Emerlad"},
    {"id":"180","market_hash_name":"test","cat":"Emerlad"}
  ],
  market_items_loaded_at: null,
};
module.exports = store;
